# fly.toml file generated for your React app
# replace <your-app-name> with the name of your Fly app

app = "maexpeditionsreact"

[build]
  builder = "heroku/buildpacks:20"
  command = "npm run build"
  # Change the path to match the location of your build directory
  dir = "./build"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

    [[services.ports.inbound]]
      port = 80

[experimental]
  allowed_public_ports = [80]

[[services.ips]]
  type = "v4"
  ip = "66.51.122.88"
